# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mom.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tmom.proto\"2\n\x0cQueueRequest\x12\r\n\x05queue\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"2\n\x0cTopicRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"/\n\x0eMessageRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\"\n\x10ReplicationReply\x12\x0e\n\x06status\x18\x01 \x01(\t2\x86\x02\n\x12ReplicationService\x12\x38\n\x14ReplicateCreateQueue\x12\r.QueueRequest\x1a\x11.ReplicationReply\x12\x38\n\x14ReplicateCreateTopic\x12\r.TopicRequest\x1a\x11.ReplicationReply\x12=\n\x17ReplicatePublishToQueue\x12\x0f.MessageRequest\x1a\x11.ReplicationReply\x12=\n\x17ReplicatePublishToTopic\x12\x0f.MessageRequest\x1a\x11.ReplicationReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mom_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_QUEUEREQUEST']._serialized_start=13
  _globals['_QUEUEREQUEST']._serialized_end=63
  _globals['_TOPICREQUEST']._serialized_start=65
  _globals['_TOPICREQUEST']._serialized_end=115
  _globals['_MESSAGEREQUEST']._serialized_start=117
  _globals['_MESSAGEREQUEST']._serialized_end=164
  _globals['_REPLICATIONREPLY']._serialized_start=166
  _globals['_REPLICATIONREPLY']._serialized_end=200
  _globals['_REPLICATIONSERVICE']._serialized_start=203
  _globals['_REPLICATIONSERVICE']._serialized_end=465
# @@protoc_insertion_point(module_scope)
